name: Lukitils
version: ${version}
main: me.lukiiy.utils.Lukitils
api-version: '1.21'
authors: [ Lukiiy ]
description: ${description}
bootstrapper: me.lukiiy.utils.Boot
folia-supported: true
dependencies:
  server:
    ViaVersion:
      required: false